Update setup
CCDirectLink/crosscode-map-editor pull request #167
Opened 2020-06-08 10:13 UTC by 2767mr

* Updated node dependencies
* Changed `npm install` to `npm ci` in travis config for more reliable builds
* Changed all typescript targets to `ES2018` for consistency
* Changed `tslint` to `eslint` because `tslint` is deprecated
  * This comes with rule changes that need to be reviewed

2020-09-13 17:00 UTC, Vegita2 requested changes
I don't like the no unused vars rule. The function gets called with the parameter anyway so removing it just makes it difficult to edit it in the future. `ngOnChanges` should also always have the `SimpleChanges` parameter.

For the other rules I'd suggest just changing them as we encounter them.

2020-09-13 17:21 UTC, 2767mr commented
> For the other rules I'd suggest just changing them as we encounter them.

Does that mean it is fine as is?

2020-09-14 11:24 UTC, Vegita2 commented
I looked through all the changes and they look good. So if it compiles we can merge it. There are probably more things that break with the updates but the basic things ahould work

2020-09-14 11:27 UTC, Vegita2 approved these changes

2020-09-15 17:35 UTC, merged