added graphical selector for some entities and fixed some issues
CCDirectLink/crosscode-map-editor pull request #271
Opened 2023-07-21 22:09 UTC by Vegita2

Added New graphical selection widget for some entities:
### Prop
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/9483499/d8b35aa2-4292-4f86-bf5c-418ad657e5ca)

### ScalableProp
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/9483499/0f680254-b549-4a3d-bc24-9bae1c7f813b)

### Enemy
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/9483499/bfcda0ec-86e8-4148-a3ac-0931a20bd8fa)

### ItemDestruct
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/9483499/e286afc9-0a86-4565-958c-26d028409040)

## other changes
- Updated Phaser to 3.60.0
- Entity copy/paste now uses the clipboard to make it easier working with multiple editor instances #267
- All `Prop` Entities should now be rendered correctly
- Improved `ScalableProp` rendering. `ends` are now rendered correctly.
- Releasing mouse button outside the canvas now properly triggers. Avoids having issues like continue dragging entities even if the mouse button was released

2023-07-24 10:36 UTC, 2767mr requested changes
Things I noticed:
* A loading indicator would be nice
* Search should include sub types (with toggle?)
* Perhaps it would look better if this is centered?
  <img width="460" alt="image" src="https://github.com/CCDirectLink/crosscode-map-editor/assets/2082553/94fe9017-f775-49da-afb1-f030972e421c">
* I think this could use some extra margin-right
  <img width="452" alt="image" src="https://github.com/CCDirectLink/crosscode-map-editor/assets/2082553/c506bbd2-d6fd-469b-9739-3ce4b14dfb11">
* There is no good way to see the full name of the character now. In my other projects I usually do `text-overflow: ellipsis` with a tooltip containing the full text. This would clash with the existing tooltips here but maybe we can figure something out.
  <img width="241" alt="image" src="https://github.com/CCDirectLink/crosscode-map-editor/assets/2082553/891cfd0b-fcba-4364-abba-92bed11aa465">
* Creating a new ScalableProp creates a 1x1 px entity (was already the case before this PR)
* I thought about opening the prop picker after double clicking props but that would probably be a bit much. Maybe opening it after creating a new prop would be nice?


Things I really liked:
* The "transparent texture"
* The size change on hover
* The red outline
* The counter in the top right of the props
* The prop rendering. That one has bothered me for a long time.

2023-07-24 10:36 UTC, 2767mr commented on webapp/src/app/services/phaser/entities/entity-manager.ts
> +			console.warn('could not parse entities from clipboard');
This should probably also show a snackbar warning

2023-07-24 14:33 UTC, Vegita2 commented
> Perhaps it would look better if this is centered?

Is this possible? the container uses `flex-wrap: wrap;` so i'm not sure how you could center them after the wrapping

> I thought about opening the prop picker after double clicking props but that would probably be a bit much. Maybe opening it after creating a new prop would be nice?

We could always trigger the double click when adding a new entity, but not sure if it's always the first thing you want to do.  I would keep it like it currently is for now and decide later with some user feedback. It could also be toggleable in the settings menu

* [ ] A loading indicator would be nice
* [ ] Search should include sub types (with toggle?)
* [ ] I think this could use some extra margin-right
   <img alt="image" width="452" src="https://user-images.githubusercontent.com/2082553/255541283-c506bbd2-d6fd-469b-9739-3ce4b14dfb11.png">
 * [ ] There is no good way to see the full name of the character now. In my other projects I usually do `text-overflow: ellipsis` with a tooltip containing the full text. This would clash with the existing tooltips here but maybe we can figure something out.
   <img alt="image" width="241" src="https://user-images.githubusercontent.com/2082553/255541917-891cfd0b-fcba-4364-abba-92bed11aa465.png">
* [x] Creating a new ScalableProp creates a 1x1 px entity (was already the case before this PR)

2023-08-03 17:21 UTC, lexisother commented
Can this be made to scroll down to the selected prop/enemy/destructible when you open the modal again?

2023-08-03 18:15 UTC, 2767mr approved these changes

2023-08-04 12:44 UTC, Vegita2 commented
@lexisother made a new issue for it #277

2023-08-04 13:16 UTC, merged