added cache for loading images/json
CCDirectLink/crosscode-map-editor pull request #300
Opened 2023-08-25 18:00 UTC by Vegita2

avoids loading the same images/json multiple times in parallel.

This should improve performance for graphical selection widget a little bit

2023-08-31 18:52 UTC, 2767mr requested changes

2023-08-31 18:52 UTC, 2767mr commented on webapp/src/app/services/phaser/helper.ts
> +			return this.cache[jsonKey];
At this point, we might as well do everything ourselves. We just need to replace the instances of `json.get(` with the helper function.
```ts
const jsonKey = key + '.json';

if (this.cache[jsonKey]) {
	return this.cache[jsonKey];
}

const promise: Promise<T | undefined> = firstValueFrom(
	Globals.httpService.resolveFile(jsonKey)
		.pipe(
			map(file => JSON.parse(file)),
			catchError(() => {
				console.warn(`Failed to resolve resource: ${jsonKey}`);
				return of(undefined);
			})
		)
	);

this.cache[jsonKey] = promise;
return promise;
```

2023-09-01 20:26 UTC, lexisother commented
This breaks the tile selector for some reason.

2023-09-02 08:01 UTC, 2767mr requested changes

2023-09-02 08:01 UTC, 2767mr commented on webapp/src/app/services/phaser/helper.ts
> +		return promise;
I completely missed this code. This doesn't work because the cache has to be dependant on the scene that is passed in as an argument.

2023-10-25 22:48 UTC, Vegita2 commented
Closing this because I don't think these changes make too much of a difference and I don't want to fix the remaining issues

2023-10-25 22:48 UTC, closed without merging