Add toggle that also shows the vanilla maps in the map selection menu
CCDirectLink/crosscode-map-editor pull request #314
Opened 2024-01-28 14:20 UTC by krypciak

2024-01-28 14:32 UTC, 2767mr approved these changes
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/2082553/07d6b3d0-0cd2-460d-a7f9-c7324637be87)

2024-01-28 15:27 UTC, krypciak commented
Swapped option order  
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/115574014/c2268241-fc4c-43a5-bc4b-1e175e1966f6)

2024-01-28 19:15 UTC, Vegita2 requested changes
looks good. Just some minor issues left.
I don't think it's necessary to disable the checkbox but I'm also ok with keeping it (if it works). 
I also recommend updating the checkbox label to specify that it's only relevant if a mod is selected

2024-01-28 19:17 UTC, krypciak commented on webapp/src/app/components/dialogs/settings/settings.component.ts
> +		this.isIncludeVanillaMapsDisabled = this.mod === 'undefined';
this mod is actually `"undefined"`, it's a string

2024-01-28 19:25 UTC, Vegita2 commented on webapp/src/app/components/dialogs/settings/settings.component.ts
> +		this.isIncludeVanillaMapsDisabled = this.mod === 'undefined';
This is how it looks in the web and electron version
![image](https://github.com/CCDirectLink/crosscode-map-editor/assets/9483499/5ccfef11-d0de-4091-9194-24975ea0264b)

2024-01-28 19:40 UTC, 2767mr commented on webapp/src/app/components/dialogs/settings/settings.component.ts
> +		this.isIncludeVanillaMapsDisabled = this.mod === 'undefined';
This does work because `this.sharedService.getSelectedMod` goes through localstorage which turns it into a string. Still not pretty though

2024-01-28 19:41 UTC, krypciak commented on webapp/src/app/components/dialogs/settings/settings.component.ts
> +		this.isIncludeVanillaMapsDisabled = this.mod === 'undefined';
I swear it works for me

2024-01-28 20:03 UTC, Vegita2 commented on webapp/src/app/components/dialogs/settings/settings.component.ts
> +		this.isIncludeVanillaMapsDisabled = this.mod === 'undefined';
Just tried it again. This happens when changing the selected mod to "None". 
So the solution should be not saving "undefined" to localstorage

2024-01-30 15:04 UTC, Vegita2 requested changes

2024-01-30 15:04 UTC, Vegita2 commented on common/src/controllers/api.ts
>  		const modDir = path.join(dir, 'mods', mods[0], 'assets');
indentation is wrong

2024-01-30 16:44 UTC, Vegita2 approved these changes

2024-01-30 16:49 UTC, merged