Added custom json configs and improved autotiles
CCDirectLink/crosscode-map-editor pull request #327
Opened 2024-07-26 15:13 UTC by Vegita2

This pull request adds two things
1. Custom JSON Configurations
2. Improved Autotiles

### Custom JSON Configurations

Users can now provide custom JSON configs for the map editor through mods.

#### Implementation Details:
- Configs from all mods are loaded and combined
- Mod configs override default configs

#### Usage:
1. Create a `map-editor` folder in your mods directory:
   ```
   CrossCode/assets/mods/[mod_name]/map-editor/
   ```
2. Add JSON files to override base map editor configs
   - Reference files: [Default Configs](https://github.com/CCDirectLink/crosscode-map-editor/tree/master/webapp/src/assets)

### Improved Autotiles

This update enhances autotile functionality and introduces a new autotile type.

#### Changes:
- Autotile definitions changed from strings to size objects
- New 4x4 autotile type implemented

#### Autotile Types:
1. Height 2 autotiles:
   - Width options: 8, 10, 12, 14
   - Example:
     <img src="https://github.com/user-attachments/assets/fedb96da-7322-4492-9cbf-6206702aa0f4" width="100%" style="image-rendering: pixelated">

2. 4x4 autotiles:
   - Example:
     ![4x4 Autotile](https://github.com/user-attachments/assets/e9177739-254c-492b-858e-765babde0759)

I made a simple tool to help creating autotile definitions: https://github.com/Vegita2/cc-autotiler

2024-07-28 14:31 UTC, 2767mr requested changes
It works exactly as I would expect. I think this will actually have a major impact on mod developers.

Just some minor nitpicks (mostly internal stuff).

One small bug I found:
After selecting a different layer, the selection box is not rendered properly.

We should probably document which .json file does what and how it is structured but I wouldn't block the PR on that.

2024-07-28 14:31 UTC, 2767mr commented on webapp/src/app/components/widgets/event-widget/event-editor/event-helper.service.ts
> +		private jsonLoader: JsonLoaderService
This seems to be unused

2024-07-28 14:31 UTC, 2767mr commented on webapp/src/app/models/map-styles.ts
>  };
You might as well do this while you're at it
```suggestion
export interface MapStyle {
	sheet: string;
	hasDoorMat?: boolean;
	walls?: WallColors;
	[key: string]: any;
}
```

2024-07-28 19:51 UTC, Vegita2 commented
> One small bug I found:
After selecting a different layer, the selection box is not rendered properly.

Can you elaborate a bit? I don't know what you mean

2024-07-28 19:54 UTC, 2767mr commented
> > One small bug I found:
> > After selecting a different layer, the selection box is not rendered properly.
> 
> Can you elaborate a bit? I don't know what you mean

Start: 
![image](https://github.com/user-attachments/assets/fd30b0c9-6577-4272-a073-fa3d9dc4f395)

After selecting "Upper":
![image](https://github.com/user-attachments/assets/e0057e3b-04da-4f78-9ad2-bba249163f84)

2024-07-28 20:23 UTC, Vegita2 commented on common/src/controllers/api.ts
> +export interface ConfigExtension<T> {
Asked claude ai to suggest some names.

- ModConfigExtension
- ModEditorConfig
- ExternalModDefinition
- ModEditorExtension
- CustomModTypeDefinition
- ModTypeAddition

Do you have any preference?

2024-07-28 20:24 UTC, 2767mr commented on common/src/controllers/api.ts
> +export interface ConfigExtension<T> {
ModEditorConfig would work for me

2024-07-28 22:30 UTC, Vegita2 commented on webapp/src/app/components/dialogs/map-settings/map-settings.component.ts
> +		this.events.updateEntities.next(true);
It fixes `Destructible` entities. Their rendering depends on the `mapStyle` property

2024-07-28 23:27 UTC, Vegita2 commented on webapp/src/app/services/phaser/BaseTileDrawer.ts
> +		if (!this.rightClickStart || !this.rightClickEnd || !phaserLayer) {
should be fixed, but would be good if you could try it out a bit. There could be some edge cases left

2024-07-28 23:27 UTC, Vegita2 commented
fixed issues

2024-07-31 08:34 UTC, 2767mr approved these changes
Tested it again and found 2 small nitpicks:
* The history texts are above the tile drawer
![image](https://github.com/user-attachments/assets/68eefa17-f3e1-4d92-9b3f-14a70e18091a)
* The tile drawer does not resize itself anymore, so on 1080p monitors it does not fit all of the arid tileset at once

2024-07-31 16:21 UTC, Vegita2 commented
> The tile drawer does not resize itself anymore, so on 1080p monitors it does not fit all of the arid tileset at once
I don't know what you mean. The tile selector always had a fixed size

2024-08-01 09:24 UTC, 2767mr commented
I was sure that it did resize at some point and did some digging. Apparently, 5 years ago in 0.4.0 it would resize itself to fit the tileset.

Obviously, I do not expect you to add it back in this PR (or at all for that matter)

2024-08-01 12:15 UTC, merged